// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Paran_Smart_Switch_vertical

#ifndef _PARAN_SMART_SWITCH_VERTICAL_UI_COMP_HOOK_H
#define _PARAN_SMART_SWITCH_VERTICAL_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_ImgButton1_create_hook( lv_obj_t *comp );

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
