// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Paran_Smart_Switch_vertical

#include "../ui.h"

// COMPONENT ImgButton1

lv_obj_t *ui_ImgButton1_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_ImgButton1;
cui_ImgButton1 = lv_imgbtn_create(comp_parent);
lv_obj_set_width( cui_ImgButton1, 64);
lv_obj_set_height( cui_ImgButton1, 64);
lv_obj_set_x( cui_ImgButton1, 140 );
lv_obj_set_y( cui_ImgButton1, -141 );
lv_obj_set_align( cui_ImgButton1, LV_ALIGN_CENTER );

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_IMGBUTTON1_NUM);
children[UI_COMP_IMGBUTTON1_IMGBUTTON1] = cui_ImgButton1;
lv_obj_add_event_cb(cui_ImgButton1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_ImgButton1, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_ImgButton1_create_hook(cui_ImgButton1);
return cui_ImgButton1; 
}

