// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Paran_Smart_Switch_vertical

#ifndef _UI_COMP_IMGBUTTON1_H
#define _UI_COMP_IMGBUTTON1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ImgButton1
#define UI_COMP_IMGBUTTON1_IMGBUTTON1 0
#define _UI_COMP_IMGBUTTON1_NUM 1
lv_obj_t *ui_ImgButton1_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
