// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Paran_Smart_Switch_vertical

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_HiddenImages;
extern lv_obj_t *ui_numb0;
extern lv_obj_t *ui_numb1;
extern lv_obj_t *ui_numb2;
extern lv_obj_t *ui_numb3;
extern lv_obj_t *ui_numb4;
extern lv_obj_t *ui_numb5;
extern lv_obj_t *ui_numb6;
extern lv_obj_t *ui_numb7;
extern lv_obj_t *ui_numb8;
extern lv_obj_t *ui_numb9;
extern lv_obj_t *ui_AMiamge;
extern lv_obj_t *ui_PMimage;
extern lv_obj_t *ui_colon;
extern lv_obj_t *ui_uiimglightonpng;
extern lv_obj_t *ui_uiimglightoffpng;
extern lv_obj_t *ui_uiimgbrightonpng;
extern lv_obj_t *ui_uiimgbrightoffpng;
extern lv_obj_t *ui_uiimgheatonpng;
extern lv_obj_t *ui_uiimgheatoffpng;
extern lv_obj_t *ui_uiimgelectriconpng;
extern lv_obj_t *ui_uiimgelectricoffpng;
extern lv_obj_t *ui_uiimgsettingonpng;
extern lv_obj_t *ui_uiimgsettingoffpng;
extern lv_obj_t *ui_Mainscroll;
extern lv_obj_t *ui_page1;
extern void ui_event_ImgButton1( lv_event_t * e);
extern lv_obj_t *ui_ImgButton1;
extern void ui_event_ImgButton2( lv_event_t * e);
extern lv_obj_t *ui_ImgButton2;
extern lv_obj_t *ui_page2;
extern void ui_event_ImgButton3( lv_event_t * e);
extern lv_obj_t *ui_ImgButton3;
extern lv_obj_t *ui_page3;
extern void ui_event_LeftArrow( lv_event_t * e);
extern lv_obj_t *ui_LeftArrow;
extern void ui_event_RightArrow( lv_event_t * e);
extern lv_obj_t *ui_RightArrow;
extern lv_obj_t *ui_ClockPanel;
extern lv_obj_t *ui_ImgAMPM;
extern lv_obj_t *ui_ImgHour10;
extern lv_obj_t *ui_ImgHour1;
extern lv_obj_t *ui_ImgColon;
extern lv_obj_t *ui_ImgMin10;
extern lv_obj_t *ui_ImgMin1;
extern lv_obj_t *ui_NavPanel;
extern void ui_event_navlightclick( lv_event_t * e);
extern lv_obj_t *ui_navlightclick;
extern void ui_event_navbrightclick( lv_event_t * e);
extern lv_obj_t *ui_navbrightclick;
extern void ui_event_navheatclick( lv_event_t * e);
extern lv_obj_t *ui_navheatclick;
extern void ui_event_navelectricclick( lv_event_t * e);
extern lv_obj_t *ui_navelectricclick;
extern void ui_event_navsettingclick( lv_event_t * e);
extern lv_obj_t *ui_navsettingclick;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

