// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Paran_Smart_Switch_vertical

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Mainscroll = NULL;lv_obj_t *ui_page1 = NULL;lv_obj_t *ui_ImgButton1 = NULL;lv_obj_t *ui_ImgButton2 = NULL;lv_obj_t *ui_page2 = NULL;lv_obj_t *ui_ImgButton3 = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_Image1 = NULL;
// event funtions
void ui_event_ImgButton1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      ui_event_light1_switch( e );
}
}

void ui_event_ImgButton2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      ui_event_light2_switch( e );
}
}

void ui_event_ImgButton3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      ui_event_Boiler_switch( e );
}
}

void ui_event_Image2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      scroll_to_page1( e );
}
}

void ui_event_Image1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      scroll_to_page2( e );
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Mainscroll = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Mainscroll, 800);
lv_obj_set_height( ui_Mainscroll, 480);
lv_obj_set_align( ui_Mainscroll, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Mainscroll,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Mainscroll, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_Mainscroll, LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_clear_flag( ui_Mainscroll, LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_Mainscroll, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_Mainscroll, LV_DIR_VER);
lv_obj_set_scroll_snap_y(ui_Mainscroll, LV_SCROLL_SNAP_CENTER);
lv_obj_set_style_bg_color(ui_Mainscroll, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Mainscroll, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Mainscroll, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Mainscroll, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_page1 = lv_obj_create(ui_Mainscroll);
lv_obj_set_width( ui_page1, lv_pct(100));
lv_obj_set_height( ui_page1, lv_pct(100));
lv_obj_set_x( ui_page1, -260 );
lv_obj_set_y( ui_page1, -136 );
lv_obj_set_align( ui_page1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_page1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_page1, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_snap_x(ui_page1, LV_SCROLL_SNAP_CENTER);
lv_obj_set_style_bg_color(ui_page1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_page1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_page1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_page1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgButton1 = lv_imgbtn_create(ui_page1);
lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_circuit1_off_png, NULL);
lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_circuit1_on_png, NULL);
lv_obj_set_width( ui_ImgButton1, 145);
lv_obj_set_height( ui_ImgButton1, 145);
lv_obj_set_x( ui_ImgButton1, 69 );
lv_obj_set_y( ui_ImgButton1, -3 );
lv_obj_set_align( ui_ImgButton1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgButton1, LV_OBJ_FLAG_CHECKABLE );   /// Flags

ui_ImgButton2 = lv_imgbtn_create(ui_page1);
lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1732143338, NULL);
lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_345358842, NULL);
lv_obj_set_width( ui_ImgButton2, 145);
lv_obj_set_height( ui_ImgButton2, 145);
lv_obj_set_x( ui_ImgButton2, -181 );
lv_obj_set_y( ui_ImgButton2, 0 );
lv_obj_set_align( ui_ImgButton2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgButton2, LV_OBJ_FLAG_CHECKABLE );   /// Flags

ui_page2 = lv_obj_create(ui_Mainscroll);
lv_obj_set_width( ui_page2, lv_pct(90));
lv_obj_set_height( ui_page2, lv_pct(90));
lv_obj_set_x( ui_page2, 53 );
lv_obj_set_y( ui_page2, -112 );
lv_obj_set_align( ui_page2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_page2, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_clear_flag( ui_page2, LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_page2, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_snap_x(ui_page2, LV_SCROLL_SNAP_CENTER);
lv_obj_set_style_bg_color(ui_page2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_page2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_page2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_page2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgButton3 = lv_imgbtn_create(ui_page2);
lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1723991977, NULL);
lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_345601881, NULL);
lv_obj_set_width( ui_ImgButton3, 145);
lv_obj_set_height( ui_ImgButton3, 145);
lv_obj_set_align( ui_ImgButton3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgButton3, LV_OBJ_FLAG_CHECKABLE );   /// Flags

ui_Image2 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image2, &ui_img_689030760);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 40
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 23
lv_obj_set_x( ui_Image2, -43 );
lv_obj_set_y( ui_Image2, -229 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Image2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Image2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_1144295435);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 40
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 23
lv_obj_set_x( ui_Image1, -39 );
lv_obj_set_y( ui_Image1, 226 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Image1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Image1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Image2, ui_event_Image2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Image1, ui_event_Image1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Mainscroll= NULL;
ui_page1= NULL;
ui_ImgButton1= NULL;
ui_ImgButton2= NULL;
ui_page2= NULL;
ui_ImgButton3= NULL;
ui_Image2= NULL;
ui_Image1= NULL;

}
