// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Paran_Smart_Switch_vertical

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Mainscroll;
extern lv_obj_t *ui_page1;
extern void ui_event_ImgButton1( lv_event_t * e);
extern lv_obj_t *ui_ImgButton1;
extern void ui_event_ImgButton2( lv_event_t * e);
extern lv_obj_t *ui_ImgButton2;
extern lv_obj_t *ui_page2;
extern void ui_event_ImgButton3( lv_event_t * e);
extern lv_obj_t *ui_ImgButton3;
extern void ui_event_Image2( lv_event_t * e);
extern lv_obj_t *ui_Image2;
extern void ui_event_Image1( lv_event_t * e);
extern lv_obj_t *ui_Image1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

