// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Paran_Smart_Switch_vertical

#ifndef _PARAN_SMART_SWITCH_VERTICAL_UI_H
#define _PARAN_SMART_SWITCH_VERTICAL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_circuit1_off_png);   // assets/circuit1_off.png
LV_IMG_DECLARE( ui_img_circuit1_on_png);   // assets/circuit1_on.png
LV_IMG_DECLARE( ui_img_1732143338);   // assets/circuit2-off.png
LV_IMG_DECLARE( ui_img_345358842);   // assets/circuit2-on.png
LV_IMG_DECLARE( ui_img_1723991977);   // assets/circuit3-off.png
LV_IMG_DECLARE( ui_img_345601881);   // assets/circuit3-on.png
LV_IMG_DECLARE( ui_img_689030760);   // assets/slide-left.png
LV_IMG_DECLARE( ui_img_1144295435);   // assets/slide-right.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
