// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Paran_Smart_Switch_vertical

#ifndef _PARAN_SMART_SWITCH_VERTICAL_UI_H
#define _PARAN_SMART_SWITCH_VERTICAL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_numb_0_png);   // assets/numb_0.png
LV_IMG_DECLARE( ui_img_numb_1_png);   // assets/numb_1.png
LV_IMG_DECLARE( ui_img_numb_2_png);   // assets/numb_2.png
LV_IMG_DECLARE( ui_img_numb_3_png);   // assets/numb_3.png
LV_IMG_DECLARE( ui_img_numb_4_png);   // assets/numb_4.png
LV_IMG_DECLARE( ui_img_numb_5_png);   // assets/numb_5.png
LV_IMG_DECLARE( ui_img_numb_6_png);   // assets/numb_6.png
LV_IMG_DECLARE( ui_img_numb_7_png);   // assets/numb_7.png
LV_IMG_DECLARE( ui_img_numb_8_png);   // assets/numb_8.png
LV_IMG_DECLARE( ui_img_numb_9_png);   // assets/numb_9.png
LV_IMG_DECLARE( ui_img_am_png);   // assets/AM.png
LV_IMG_DECLARE( ui_img_pm_png);   // assets/PM.png
LV_IMG_DECLARE( ui_img_colon_png);   // assets/colon.png
LV_IMG_DECLARE( ui_img_light_on_png);   // assets/light_on.png
LV_IMG_DECLARE( ui_img_light_off_png);   // assets/light_off.png
LV_IMG_DECLARE( ui_img_bright_on_png);   // assets/bright_on.png
LV_IMG_DECLARE( ui_img_bright_off_png);   // assets/bright_off.png
LV_IMG_DECLARE( ui_img_heat_on_png);   // assets/heat_on.png
LV_IMG_DECLARE( ui_img_heat_off_png);   // assets/heat_off.png
LV_IMG_DECLARE( ui_img_electric_on_png);   // assets/electric_on.png
LV_IMG_DECLARE( ui_img_electric_off_png);   // assets/electric_off.png
LV_IMG_DECLARE( ui_img_setting_on_png);   // assets/setting_on.png
LV_IMG_DECLARE( ui_img_setting_off_png);   // assets/setting_off.png
LV_IMG_DECLARE( ui_img_circuit1_off_png);   // assets/circuit1_off.png
LV_IMG_DECLARE( ui_img_circuit1_on_png);   // assets/circuit1_on.png
LV_IMG_DECLARE( ui_img_1732143338);   // assets/circuit2-off.png
LV_IMG_DECLARE( ui_img_345358842);   // assets/circuit2-on.png
LV_IMG_DECLARE( ui_img_1723991977);   // assets/circuit3-off.png
LV_IMG_DECLARE( ui_img_345601881);   // assets/circuit3-on.png
LV_IMG_DECLARE( ui_img_689030760);   // assets/slide-left.png
LV_IMG_DECLARE( ui_img_1144295435);   // assets/slide-right.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
