// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Paran_Smart_Switch

#include "ui.h"

void ui_event_light1_switch(lv_event_t * e)
{
	// Your code here
}

void ui_event_light4_switch(lv_event_t * e)
{
	// Your code here
}

void ui_event_light3_switch(lv_event_t * e)
{
	// Your code here
}

void ui_event_light2_switch(lv_event_t * e)
{
	// Your code here
}

void ui_event_Boiler_switch(lv_event_t * e)
{
	// Your code here
}




void scroll_to_page2(lv_event_t * e)
{
	// Your code here
}

void scroll_to_page1(lv_event_t * e)
{
	// Your code here
}

void nav_light_click(lv_event_t * e)
{
	// Your code here
}

void nav_bright_click(lv_event_t * e)
{
	// Your code here
}

void nav_heat_click(lv_event_t * e)
{
	// Your code here
}

void nav_electric_click(lv_event_t * e)
{
	// Your code here
}

void nav_setting_click(lv_event_t * e)
{
	// Your code here
}

void scroll_to_page_prev(lv_event_t * e)
{
	// Your code here
}

void scroll_to_page_next(lv_event_t * e)
{
	// Your code here
}
