// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Paran_Smart_Switch_vertical

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_event_light1_switch(lv_event_t * e);
void ui_event_light2_switch(lv_event_t * e);
void ui_event_Boiler_switch(lv_event_t * e);
void scroll_to_page_prev(lv_event_t * e);
void scroll_to_page_next(lv_event_t * e);
void nav_light_click(lv_event_t * e);
void nav_bright_click(lv_event_t * e);
void nav_heat_click(lv_event_t * e);
void nav_electric_click(lv_event_t * e);
void nav_setting_click(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
